[package]
name = "rsstg"
version = "0.2.1"
authors = ["arcade"]
edition = "2018"

[dependencies]
anyhow = "*"
atom_syndication = { version = "*", features = [ "with-serde" ] }
chrono = "*"
config = "*"
futures = "*"
futures-util = "*"
lazy_static = "*"
regex = "*"
reqwest = { version = "*", features = [ "brotli", "gzip", "deflate" ]}
rss = { version = "*", features = [ "from_url" ] }
sedregex = "*"
sqlx = { version = "*", features = [ "postgres", "tls", "runtime-tokio-native-tls", "chrono" ] }
#telegram-bot = "*"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot" }
tokio = { version = "1.2", features = [ "macros", "net", "rt-multi-thread", "time" ] }

[profile.release]
lto = true
codegen-units = 1
