[package]
name = "rsstg"
version = "0.2.13"
authors = ["arcade"]
edition = "2018"

[dependencies]
anyhow = "*"
async-std = { version = "*", features = [ "tokio1" ] }
atom_syndication = { version = "*", features = [ "with-serde" ] }
chrono = "*"
config = { version = "*", default-features = false, features = [ "toml" ] }
futures = "*"
futures-util = "*"
lazy_static = "*"
regex = "*"
reqwest = { version = "^0.11", features = [ "brotli", "gzip", "deflate" ]}
rss = { version = "*", features = [ "from_url" ] }
sedregex = "*"
sqlx = { version = "*", features = [ "postgres", "tls", "runtime-async-std-rustls", "chrono" ] }
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot" }

#surf = { version = "*",  default-features = false, features = [ "middleware-logger", "encoding", "h1-client-rustls" ] }

[profile.release]
lto = true
codegen-units = 1
